ner: "https://drive.google.com/file/d/1GZwp5E0yK-q-17JWznZx4eLR9zKVsJK6/view?usp=sharing"
ac: "https://drive.google.com/file/d/1WEqsBbTSibrGmq_O0zEsU5rTmohVaMgQ/view?usp=sharing"
roberta: "https://dl.fbaipublicfiles.com/biolm/RoBERTa-base-PM-M3-Voc-distill-align-hf.tar.gz"
entity:
  model: "https://drive.google.com/file/d/11VSLCZAH3D8JyYFH2zkEw_VLuRiB1tNe/view?usp=sharing"
  tokenizer: "https://drive.google.com/file/d/1STXM3w0PIpWOuN0d7X2NhCWTHuNPYBW2/view?usp=sharing"
fulltext: "https://drive.google.com/file/d/1kAO5EILJfIT3w8RbrRc3kVi6bUX9quaQ/view?usp=sharing"
